# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-01 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('birthday', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.CharField(max_length=20, verbose_name='姓名')),
                ('score', models.CharField(max_length=20, verbose_name='姓名')),
                ('Email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
    ]
